# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 032862d1021101d606dae0de13ecf569e81f2522d526448d1ec023822ace54c696f67ff8424d5945beac4d7d453a329ba46984a505211111dc691066a4d54d19

test:
  secret_key_base: 9a11c1d9a50d85385ccfd204516abae6ebc748b5039e44636b3f9a861d2fd0a066e89ec074442eb5f204da0c9659b587a7f5816024bd27090459c813b8ab6d8a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
